// client-cp/src/lib/components/VideoStream.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import type { Writable } from 'svelte/store';

	export let stream: Writable<MediaStream | null>;
	export let muted: boolean = false;
	export let title: string = '';

	let videoElement: HTMLVideoElement;

	onMount(() => {
		const unsubscribe = stream.subscribe((value) => {
			videoElement.srcObject = value;
		});

		return () => {
			unsubscribe();
		};
	});
</script>

<video bind:this={videoElement} {muted} autoplay playsinline {title}></video>

<style>
	video {
		width: 300px;
		height: 200px;
		margin: 10px;
		background-color: #ddd;
	}
</style>

// client-cp/src/components/VideoStream.tsx
import React, { useEffect, useRef } from 'react';

interface VideoStreamProps {
    stream: MediaStream | null;
    muted?: boolean;
    title?: string;
}

const VideoStream: React.FC<VideoStreamProps> = ({ stream, muted = false, title = '' }) => {
    const videoElement = useRef<HTMLVideoElement>(null);

    useEffect(() => {
        if (videoElement.current) {
            videoElement.current.srcObject = stream;
        }
    }, [stream]);

    return (
        <video
            ref={videoElement}
            muted={muted}
            autoPlay
            playsInline
            title={title}
            style={{
                width: '300px',
                height: '200px',
                margin: '10px',
                backgroundColor: '#ddd',
            }}
        ></video>
    );
};

export default VideoStream;
